purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5955961
  brandStrength: 0.9232008
  lightness: 0.2271751
  brandColors:
    - '#FFFFFF'
    - '#070707'
    - '#535156'
    - '#0AFFFF'
    - '#FC4757'
  rhythmicContrast: 0.7910848
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: 'Seishonagon '
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5150376
layout_spectrum: 1
